name: clone_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  velocity_x: ^4.1.0
  get: ^4.6.5
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  permission_handler: ^10.0.0
  image_picker: ^0.8.7+5
  shared_preferences: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: mont
      fonts:
        - asset: assets/fonts/mont.ttf
    - family: mont_bold
      fonts:
        - asset: assets/fonts/mont_bold.ttf
    - family: mont_light
      fonts:
        - asset: assets/fonts/mont_light.ttf
    - family: mont_semi
      fonts:
        - asset: assets/fonts/mont_semi.ttf
